swagger:
  enable: true
spring:
  application:
    name: wechat-pay
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://42.194.140.230:3306/xdclass?useUnicode=true&characterEncodin=UTF-8&useSSL=false
      username: root
      password: Kehong0028..
      max-active: 200
      max-wait: 60000
      min-idle: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
wxpay:
  appid: wx025575eac69a2d5b
  appsecret: f5b6730c592ac15b8b1a5aeb8948a9f3
wxopen:
  appid: wxu43ykka27h78m2ig
  appsecret: p3336mt274i0z0i85050i85c286p8847
  redirect_url: http://16webtest.ngrok.xiaomiqiu.cn
